name: 03.Trivy CVE Scan

on:
  schedule:
    - cron: "20 2 * * SUN"
  workflow_dispatch:
jobs:
  trivy-cve-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.67.2
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest'
          format: 'sarif'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.sarif'
          limit-severities-for-sarif: 'true'
        env:
          TRIVY_VEX: ''
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-report.sarif'
   